/*
 * 配置服务API
 *
 * 配置服务API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config
// CursorConfigTemplatesResponseData struct for CursorConfigTemplatesResponseData
type CursorConfigTemplatesResponseData struct {
	Extra CursorExtra `json:"extra,omitempty"`
	Items []ConfigTemplate `json:"items,omitempty"`
}
