/*
 * 配置服务API
 *
 * 配置服务API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config
// UpdateConfigGroupReq struct for UpdateConfigGroupReq
type UpdateConfigGroupReq struct {
	// 配置ID
	Id string `json:"id,omitempty"`
	// 名称
	Name string `json:"name,omitempty"`
}
