/*
 * 配置服务服务端API
 *
 * 配置服务服务端API.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config
// CreateConfigReq struct for CreateConfigReq
type CreateConfigReq struct {
	TenantId string `json:"tenantId,omitempty"`
	ReferId string `json:"referId,omitempty"`
	TemplateId int64 `json:"templateId,omitempty"`
	Key string `json:"key,omitempty"`
	Value string `json:"value,omitempty"`
}
