/*
 * 配置服务服务端API
 *
 * 配置服务服务端API.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config
// UpdateConfigReq struct for UpdateConfigReq
type UpdateConfigReq struct {
	Id int64 `json:"id,omitempty"`
	Value string `json:"value,omitempty"`
}
