/*
 * 配置服务API
 *
 * 配置服务API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config
// RetrieveConfigByKeyReq struct for RetrieveConfigByKeyReq
type RetrieveConfigByKeyReq struct {
	ResourceId string `json:"resourceId,omitempty"`
	Key string `json:"key,omitempty"`
}
