/*
 * 配置服务API
 *
 * 配置服务API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config
// UpdateConfigReq struct for UpdateConfigReq
type UpdateConfigReq struct {
	// 配置ID
	Id string `json:"id,omitempty"`
	// json格式的键值对数据
	Value map[string]interface{} `json:"value,omitempty"`
}
