/*
 * 配置服务API
 *
 * 配置服务API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config
// BatchRetrieveConfigsResponse struct for BatchRetrieveConfigsResponse
type BatchRetrieveConfigsResponse struct {
	// 配置ID列表
	Ids []string `json:"ids,omitempty"`
}
