/*
 * 配置服务API
 *
 * 配置服务API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config
// PageConfigGroupsResponseData struct for PageConfigGroupsResponseData
type PageConfigGroupsResponseData struct {
	// 页码
	PageNo int32 `json:"pageNo,omitempty"`
	// 翻页大小
	PageSize int32 `json:"pageSize,omitempty"`
	// 页数
	PageCount int32 `json:"pageCount,omitempty"`
	// 总数量
	Total int32 `json:"total,omitempty"`
	Content []ConfigGroup `json:"content,omitempty"`
}
