/*
 * 配置服务API
 *
 * 配置服务API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config
// RetrieveConfigGroupByNameResponse struct for RetrieveConfigGroupByNameResponse
type RetrieveConfigGroupByNameResponse struct {
	Code int64 `json:"code,omitempty"`
	Msg string `json:"msg,omitempty"`
	Data ConfigGroup `json:"data,omitempty"`
}
