/*
 * 配置服务API
 *
 * 配置服务API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config
// CreateConfigGroupReq struct for CreateConfigGroupReq
type CreateConfigGroupReq struct {
	// 名称
	Name string `json:"name,omitempty"`
}
