/*
 * 配置服务API
 *
 * 配置服务API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config
// BatchRetrieveByKeysReq struct for BatchRetrieveByKeysReq
type BatchRetrieveByKeysReq struct {
	// keys
	Keys []string `json:"keys,omitempty"`
	// 资源ID
	ResourceId string `json:"resourceId,omitempty"`
}
