/*
 * 配置服务API
 *
 * 配置服务API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config
// InlineResponse2004 struct for InlineResponse2004
type InlineResponse2004 struct {
	Code int64 `json:"code,omitempty"`
	Msg string `json:"msg,omitempty"`
	Data InlineResponse2004Data `json:"data,omitempty"`
}
