/*
 * 配置服务API
 *
 * 配置服务API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config
// InlineResponse2003 struct for InlineResponse2003
type InlineResponse2003 struct {
	Code int64 `json:"code,omitempty"`
	Msg string `json:"msg,omitempty"`
	Data InlineResponse2003Data `json:"data,omitempty"`
}
