/*
 * 配置服务服务端API
 *
 * 配置服务服务端API.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config
// CreateConfigRspAllOf struct for CreateConfigRspAllOf
type CreateConfigRspAllOf struct {
	Data Config `json:"data,omitempty"`
}
