/*
 * 配置服务API
 *
 * 配置服务API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config
// InlineResponse20012 struct for InlineResponse20012
type InlineResponse20012 struct {
	Code int64 `json:"code,omitempty"`
	Msg string `json:"msg,omitempty"`
	Data InlineResponse20012Data `json:"data,omitempty"`
}
