/*
 * 配置服务API
 *
 * 配置服务API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config
// CreateConfigTemplateReq struct for CreateConfigTemplateReq
type CreateConfigTemplateReq struct {
	// 组ID
	GroupId string `json:"groupId,omitempty"`
	// 模版ID
	TemplateId string `json:"templateId,omitempty"`
	// 对应的字段名
	Key string `json:"key,omitempty"`
	// json格式的键值对数据
	Value map[string]interface{} `json:"value,omitempty"`
}
