/*
 * 配置服务API
 *
 * 配置服务API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config
// SortSpec struct for SortSpec
type SortSpec struct {
	// 排序字段
	Property string `json:"property,omitempty"`
	// 排序类型，0默认，1升序，2降序
	Type string `json:"type,omitempty"`
	// 是否忽略大小写
	IgnoreCase string `json:"ignoreCase,omitempty"`
}
