/*
 * 配置服务API
 *
 * 配置服务API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config
// InlineResponse2007 struct for InlineResponse2007
type InlineResponse2007 struct {
	Code int64 `json:"code,omitempty"`
	Msg string `json:"msg,omitempty"`
	Data InlineResponse2007Data `json:"data,omitempty"`
}
