/*
 * 配置服务API
 *
 * 配置服务API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config
// BatchRetrieveConfigTemplateByKeysReq struct for BatchRetrieveConfigTemplateByKeysReq
type BatchRetrieveConfigTemplateByKeysReq struct {
	Keys []string `json:"keys,omitempty"`
}
