/*
 * 配置服务API
 *
 * 配置服务API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config
// CursorConfigGroupsRspData struct for CursorConfigGroupsRspData
type CursorConfigGroupsRspData struct {
	Extra CursorExtra `json:"extra,omitempty"`
	Items []ConfigGroup `json:"items,omitempty"`
}
