/*
 * 配置服务服务端API
 *
 * 配置服务服务端API.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config
// BaseResponse struct for BaseResponse
type BaseResponse struct {
	Errcode int32 `json:"errcode,omitempty"`
	Errmsg string `json:"errmsg,omitempty"`
}
