/*
 * 配置服务API
 *
 * 配置服务API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package config
// DeleteRsp struct for DeleteRsp
type DeleteRsp struct {
	Code int64 `json:"code,omitempty"`
	Msg string `json:"msg,omitempty"`
	// 暂时未返回数据
	Data *interface{} `json:"data,omitempty"`
}
